### ISSUE TITLE
uv-l-filesToVirtuoso

### ISSUE THREAD

**Issue by skodape** [UnifiedViews/Plugins#176]
It looks like it does not work in latest develop (2de28e3).

The error message is:
```
Execution failed because: Error executing queryeu.unifiedviews.dpu.DPUException: Error executing query 
at eu.unifiedviews.plugins.loader.filestovirtuoso.VirtuosoLoader.innerExecute(VirtuosoLoader.java:327) 
at eu.unifiedviews.helpers.dpu.exec.AbstractDpu.execute(AbstractDpu.java:117) 
at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.executeInstance(DPUExecutor.java:232) 
at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.execute(DPUExecutor.java:370) 
at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.run(DPUExecutor.java:452) 
at java.lang.Thread.run(Thread.java:745) 
Caused by: virtuoso.jdbc4.VirtuosoException: Permissions of unauthenticated user are broader than new permissions of user "TODO_CHANGE_THIS_MOCK" on specific graph 
at virtuoso.jdbc4.VirtuosoResultSet.process_result(VirtuosoResultSet.java:344) 
at virtuoso.jdbc4.VirtuosoResultSet.getMoreResults(VirtuosoResultSet.java:84) 
at virtuoso.jdbc4.VirtuosoPreparedStatement.sendQuery(VirtuosoPreparedStatement.java:87) 
at virtuoso.jdbc4.VirtuosoPreparedStatement.executeQuery(VirtuosoPreparedStatement.java:163) 
at eu.unifiedviews.plugins.loader.filestovirtuoso.VirtuosoLoader.innerExecute(VirtuosoLoader.java:301) 
... 5 more 
```

I also try few different versions:
uv-l-filesToVirtuoso-1.7.1-SNAPSHOT-2de28e3 - FAIL
uv-l-filesToVirtuoso-1.7.0-SNAPSHOT-9daa0fc - FAIL
uv-l-filesToVirtuoso-1.7.0-SNAPSHOT-c488761 - FAIL
uv-l-filesToVirtuoso-1.7.0-SNAPSHOT-02d0466 - OK
Last commit we know it was workign for: 02d046674101bc5578311401559fdae72e1eb28a

There are different exceptions for some versions.

**Comment by eea03** [comment]
Well, this exception is thrown when trying to set permissions for user created by DPU. This fails because Virtuoso unauthenticated user ("nobody") has wider permissions than we are actually trying to set for created user; This can be solved only by decreasing rights for unauthenticated user;
Question is what rights should unauthenticated user have; It seems he has quite high rights for all graphs by default; I would expect unauthenticated user has no rights at all or maybe read rights at most;
Another question is if this should be configured by DPU or this should be prerequisite configuration of Virtuoso. As Virtuoso loader DPU by default sets global read right for created users, maximum right for nobody can also be read right (nobody user cannot have broader rights than any of users);

So to conclude:
In order to run DPU properly, just lower rights for unauthenticated user; Execute SQL in Virtuoso:
no rights: DB.DBA.RDF_DEFAULT_USER_PERMS_SET ('nobody', 0);
read rights: DB.DBA.RDF_DEFAULT_USER_PERMS_SET ('nobody', 1);

Then DPU should work as expected;
Further discussion needed about what rights should unauthenticated user have and if this should be Virtuoso configuration or if it should be handled by DPU

**Comment by tomas-knap** [comment]
Ok, but what caused that when using some of the previous versions of the DPU (see above), the problem does not occur? It seems that this is a problem of target database setting, right? Was there an update of the virtuoso driver in the meanwhile? Because otherwise it is not clear to me what changes in the DPU itself in the last weeks could have caused this problem

**Comment by eea03** [comment]
Creating users in Virtuoso is a new feature, in previous versions, DPU was not attempting to create users and setting rights on graphs for them. Actually this feature was implemented simultaneously with upgrade to plugins 2.0; That is why the mentioned last commit (from feature branch) was working; However after merge this new functionality is causing the problems;
Now as I am looking closer to this, we have another problem; DPU is actually creating users as organizations from UV (user in Virtuoso = organization in UV); However if UV is running in user mode, no organization exists for user; Even worse, DPUContext.getOrganization() throws NullPointerException (but this is a bug in UV Core).
Possible solutions for this could be to check if organization exists and if not, use pipeline owner to create Virtuoso user; Or maybe this creating of users in Virtuoso can be turned off either in DPU configuration or globally in config.properties

**Comment by tomas-knap** [comment]
The problematic commit is: https://github.com/UnifiedViews/Plugins/commit/c4887615ce215882993f72dada3f858cf3f92474

@mkl-eea-sk should have more info to the commit

Yes, if UV is running in user mode, user in Virtuoso has to be created based on user in UV.

**Comment by eea03** [comment]
Unfortunately I don't know the background behind this feature so @mkl-eea-sk should provide more information;
However, this setting of target Virtuoso can be also set by DPU automatically but this would mean we always deny access for unauthenticated users, which not always has to be desired.
I don't really know what are requirements for eDem for this DPU so we should wait for @mkl-eea-sk 
I agree with the checkbox;

**Comment by skrchnavy** [comment]
Checkbox requires migration of configuration, for this moment it is too late to add such functionality. Proposed is to be able to turn on/off this feature from backend config.

In next version we can improve it.

**Comment by eea04** [comment]
Nobody user must have read-only access on all graphs. This is to ensure that the public (i.e. unathenticated users) can query all graphs.
mkl has know-how about this DPU, and it's not quite finished yet (mostly aspects regarding integration with virtuoso) so he should deal with this.

**Comment by tomas-knap** [comment]
See https://github.com/UnifiedViews/Plugins/issues/179
