### ISSUE TITLE
l-rdfToVirtuoso doesn't use symbolic name set by t-filesToRdf?

### ISSUE THREAD

**Issue by jindrichmynarz** [UnifiedViews/Plugins#224]
When I set a fixed output symbolic name in t-filesToRdf and pipe the output of this DPU to l-rdfToVirtuoso (compiled from f3b17d1dfeb306a7fc17e5fb5e84d8bf6b7290bd) and configure it to "per graph" mode I expect it to use the fixed output symbolic name as the URI of the named graph uploaded to Virtuoso. Instead, it uploads the data to a named graph identified via an internal UnifiedViews URI (e.g., <http://unifiedviews.eu/resource/internal/dataunit/exec/26/dpu/46/du/1/entry/1>).

Is it correct to expect that l-rdfToVirtuoso uses the fixed output symbolic name as a named graph URI?

**Comment by mkl-eea-sk** [comment]
This is bug in FilesToRdf, which does not set (nor even let you choose) the VirtualGraph metadata. Symbolic name, as such, cannot be used in rdfToVirtuoso as Graph name, since it may not be http:// URI. It is just plain string (Unicode enabled).
rdfToVirtuoso has two options what to use in per graph mode:
- virtual graph metadata
- internal graph name
