### ISSUE TITLE
e-silkLinker: "No such file or directory" exception

### ISSUE THREAD

**Issue by jindrichmynarz** [UnifiedViews/Plugins#342]
e-silkLinker (compiled from 0059daa20b6ad6a5daf4b83f5e21ca80bbab0de2) probably creates files. Executing is fails with the following exceptions:

`RDFException: /opt/var/lib/unifiedviews/working/exec_706/working/dpu_1470/dpu/verify.ttl (No such file or directory)`

`RDFException: /opt/var/lib/unifiedviews/working/exec_706/working/dpu_1470/dpu/confirmed.ttl (No such file or directory)`

**Comment by jindrichmynarz** [comment]
@tomas-knap: What is the current status? This issue blocks the majority of the remaining SK COMSODE pipelines, so it would be great if it was resolved as soon as possible.

**Comment by tomas-knap** [comment]
Working on that

**Comment by tomas-knap** [comment]
I was not able to reproduce. 

Since Silk is executed as external proces, it may be executed under a different user than unifiedviews backend and can lack permissions to write to /backend/working. As a result, such files are then not created and the exception you wrote appears. @jindrichmynarz Can you please confirm that?

**Comment by jindrichmynarz** [comment]
The DPU does not allow to specify under which user Silk is run. If the DPU runs Silk under a user that does not have a write permission into the working directory, then I consider it as a bug of the DPU.

What do you want me to confirm? That the files are not created?

**Comment by jindrichmynarz** [comment]
When I run a pipeline with e-silkLinker, not even the execution directory in working directory is created.

**Comment by tomas-knap** [comment]
Under which user do you run unifiedviews? Under which user are you logged on? Does the user you are logged on have the write permission to backend/working dir?

**Comment by jindrichmynarz** [comment]
I don't specify that. UnifiedViews is run under the default user that ODN 1.1.0 specifies. Looking at the upstart scripts for UnifiedViews, it seems that it is the user `unifiedviews`, who owns the working directory.

**Comment by tomas-knap** [comment]
It is strange that the working directory is not created. Because before the Silk is executed as the separate process, "conf.xml" file is created in the working directory. So if you run Silk DPU in debug mode, there must be "conf.xml" file in the working directory of the corresponding execution (/opt/var/lib/unifiedviews/working/exec_706/working/dpu_1470/dpu/conf.xml, with number being a bit different in your case). 

If not, basically you should get error with any pipeline execution which requires access to working directory.

**Comment by jindrichmynarz** [comment]
I ran the pipeline in the non-debug mode. When I run it in the debug mode, the execution directory is created and contains the `conf.xml` file. However, the pipeline still fails with the same error.

**Comment by jindrichmynarz** [comment]
I think it is highly likely that while UnifiedViews has write permission for the working directory (otherwise no pipeline would work), the user under which Silk is run as an external process does not. The question is why e-silkLinker does not run Silk under the same user as UnifiedViews runs.

**Comment by tomas-knap** [comment]
@jindrichmynarz, please build/test e-silkLinker DPU from https://github.com/UnifiedViews/Plugins/pull/346.

**Comment by jindrichmynarz** [comment]
#346 resolves the issue.
