### ISSUE TITLE
t-tabular: row class empty but rdf:type still created

### ISSUE THREAD

**Issue by skarampatakis** [UnifiedViews/Plugins#363]
Hi, I am using t-tabular to map csv data to my ontology. I have the Row class entry field empty as I don't want to create a class. But after I save the pipeline, and run it the default Row Class is still created. I found also that after save, if I see the details of th DPU the Row class is present again so maybe this is a bug.

**Comment by tomas-knap** [comment]
This is a feature ;-) Thus, when you do not fill any target class, the default is used. If this is an issue, you may add t-sparqlUpdate after the t-tabular to DELETE the unwanted triples. Or it should be straightforward to adjust the behavior of t-tabular so that it does not generate these triples if the "class for the row entity" is empty. If you will do so, you may simple prepare pull request with that change, we will incorporate.

**Comment by tomas-knap** [comment]
If you need help with adjustments of the tabular, please contact me, e.g., via skype "nappy_cz"
