### ISSUE TITLE
duplicate entry symbolic name - message needs to be more useful.

### ISSUE THREAD

**Issue by pma42** [UnifiedViews/Plugins#383]
Hi,

With a clean database/clean install I'm getting the following message from one of the 
pipelines I'm looking at :

Duplicate entry found for symbolic name: ce20118b0cd0eb4b0f4e24803c628cb1eeb14250

It's not at all obvious - what this is related to or whether I can fix the problem (as far as I can
tell the uuid isn't in the input data).

Paul.

**Comment by tomas-knap** [comment]
Can you please provide me with the export of the pipeline? Also if possible, please try to let me know which DPU throws that (or between which DPU executions it was thrown).

This typically happens if there is more than one entry (file or RDF graph) with the same symbolic name as the input to certain DPU

**Comment by paulmassey42** [comment]
Hello,

It was the filesDownload DPU which was throwing up the exception.

I managed to get around the error by specifying the exact file to be used
(in both the uri and the
filename fields in the dpu configuration table). As there's a long list of
files it'll be a little time
consuming to fill it all in (rather than just all files from that directory
using the uri "file:///dir").

I was expecting a filename to be returned or some such rather than the
uuid. I tried recreating
the pipeline from scratch (filesDownload "all from a giver directory" and
filterFiles "subset of the
files") and got the same message (logfiles didn't really help). Specifying
the exact files meant I
got further.

The is on the 2.3.0 version rather than the latest.

Paul.

**Comment by erikap** [comment]
I'm having the same issue with the filesDownload DPU when specifying a folder as URI (e.g. file:///path/to/dir). If no filename is specified, one will be generated based on the URI (see https://github.com/UnifiedViews/Plugins/blob/master/e-filesDownload/src/main/java/eu/unifiedviews/plugins/extractor/filesdownload/FilesDownload.java#L191). For a directory URI , this will result in the same generated filename for each file in the directory causing the duplicate entry symbolic name error.

**Comment by tomas-knap** [comment]
It now behaves in a way that if there is no filename for the directory, one is generated, unique for each entry. If there is filename for the directory, it is used as a prefix for all files within that directory
