### ISSUE TITLE
T-RDFToFiles should log progress

### ISSUE THREAD

**Issue by jakubklimek** [UnifiedViews/Plugins#80]
T-RDFToFiles should log progress. Now it just says executing.... and stays like this for hours.

**Comment by AndreAga** [comment]
Hi @jakubklimek , do you refer to log (debug) messages or contex messages?

**Comment by tomas-knap** [comment]
Current status is that "private String exportGraph(URI[] uris, String fileName) throws DataUnitException, ExportFailedException { " method now only logs: "LOG.debug("Exporting Graph "+ config.getOutGraphName());", but it may than take hourse. So the idea, @jakubklimek  had, was to provide more information about the process of file creation. 

Nevertheless, that would basically mean to be able to see inner state of the function connection.export(), which basically means to implement some openRDF handler, so that report may be provided about the progress of the file creation. When implementing such handler, transactions must be properly handled so that the whole export process is meant to be one transaction. 

I would postpone this issue now, there are High priority issues.

**Comment by mkl-eea-sk** [comment]
transactions are supported in 2.8.0 sesame, until then, talking about transactions does not make sense

**Comment by mkl-eea-sk** [comment]
and what do you expect from connection.export working in transaction? it either goes well, or throws an expection. if it throws an exception, one has to assure that file is not added to output data unit. thats all. simple. and it is only in case, when 'skip file on error' is checked in configuration.

**Comment by skrchnavy** [comment]
fixed in 471a95756506abfb44740d8011b87c0ae2cfbfd5
