### ISSUE TITLE
Align DPUs: t-SPARQL*

### ISSUE THREAD

**Issue by skrchnavy** [UnifiedViews/Plugins#92]
There are few DPUs related to SPARQL queries

Official plugins repo contains the following DPUs for executing SPARQL queries:
* t-sparql in UnifiedViews/Plugins
* t-sparqlSelect in UnifiedViews/Plugins
* t-sparqConstruct in mff-uk/DPUs
* t-sparqUpdate in mff-uk/DPUs

t-sparql shall be deprecated (not  to include into release) and keep all t-sparql[Select | Construct | Update] in UnifiedViews/Plugins repo.

**Comment by jakubklimek** [comment]
+1

**Comment by tomas-knap** [comment]
Note: 
t-sparqlUpdate/t-sparqlConstruct does not support multiple tabs for multiple Update/Construct queries. Created issue: https://github.com/mff-uk/DPUs/issues/98

Note: In order to migrate DPUs from mff-uk/DPUs, we have to solve the alignment of helpers before, because mff-uk/DPUs use CUNI helpers.

**Comment by skrchnavy** [comment]
Also documentation in Readme.md file in proper directories shall be updated to reflect changes and also version history shall be updated.

**Comment by tomas-knap** [comment]
TODO: Adjust version of t-sparqlSelect, t-sparqlUpdate to 2.0.

**Comment by tomas-knap** [comment]
update history, these DPUs were imported from CUNI repo, start with 1.X. History will be maintained in the future properly
